[project]
name = "sora2-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai>=2.2.0",
    "python-dotenv>=1.0.0",
    "print-color>=0.4.6",
]
